apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: jameskubeproject
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: jameskubeproject
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
  type: NodePort
